version: '3'
services:
  postgresdb:
    container_name: postgresdb
    hostname: postgresdb
    image: postgres:12.2-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  # arvatobank:
  #    build: arvatobank
  #    hostname: arvatobank
  #    container_name: arvatobank
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - postgresdb

