version: '3'
services:
  postgresdb:
    container_name: postgresdb
    hostname: postgresdb
    image: postgres:12.2-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  arvatobank:
    build:
      context: ./arvatobank
      dockerfile: Dockerfile-dev
    hostname: arvatobank
    container_name: arvatobank
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
      - mailhog

