version: '3'
services:
  arvatobank:
     build: arvatobank
     hostname: arvatobank
     container_name: arvatobank
     ports:
       - "8080:8080"
     depends_on:
       - mongodb
  db:
    container_name: db
    hostname: db
    build: db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=arvatobank

